# Generated by Django 4.0.2 on 2022-04-09 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumeranker', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
