# Generated by Django 4.0.2 on 2022-04-09 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resumeranker', '0002_delete_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='myUploadFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myfiles', models.FileField(upload_to='')),
            ],
        ),
    ]
