# Generated by Django 4.0.2 on 2022-04-09 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeranker', '0004_myuploadfile_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(null=True)),
                ('name', models.CharField(max_length=64)),
                ('collegeName', models.CharField(max_length=100)),
                ('degree', models.CharField(max_length=200)),
                ('graduationYear', models.CharField(max_length=200)),
                ('yearsOfExperience', models.CharField(max_length=200)),
                ('companiesWorkedAt', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=200)),
                ('skills', models.TextField(max_length=255)),
                ('Location', models.TextField(max_length=200)),
                ('emailAddress', models.EmailField(max_length=254)),
            ],
        ),
        migrations.RemoveField(
            model_name='myuploadfile',
            name='text',
        ),
    ]
