# Generated by Django 4.0.2 on 2022-04-09 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeranker', '0005_data_remove_myuploadfile_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='Location',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='collegeName',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='companiesWorkedAt',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='degree',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='designation',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='emailAddress',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='graduationYear',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='name',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='skills',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='data',
            name='yearsOfExperience',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
